- block:
    - name: create dir
      file:
        path: "{{item.dest}}"
        state: directory
#        mode: "{{mode}}" # If mode is not specified and the destination filesystem object does exist, the mode of the existing filesystem object will be used.
        owner: "{{owner}}"
        group: "{{group}}"
      loop: "{{overwrite_files}}"
      vars:
        overwrite_files: "{{overwrite_files_nginx}}"
        group: nginx
        owner: nginx
        mode: 0755
        force: yes

    - name: overwrite files
      template:
        src: "{{item.src | basename}}"
        dest: "{{item.dest}}/{{item.src | basename}}"
        force: "{{ force | default('yes') }}"
#        mode: "{{mode}}" # If mode is not specified and the destination file does exist, the mode of the existing file will be used.
        owner: "{{owner}}"
        group: "{{group}}"
      loop: "{{overwrite_files}}"
      vars:
        overwrite_files: "{{overwrite_files_nginx}}"
        group: nginx
        owner: nginx
        mode: 0644
        force: yes

  become: yes
