---
- name: Get IP from fact
  set_fact:
    ip: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"

- name: Create folder
  file:
    path: /mnt/log
    state: directory

- name: Get Logs K3s
  shell: journalctl -eu k3s.service > /mnt/log/logs_k3s.txt

- name: Get Logs awx-web
  shell: kubectl -n awx  logs deploy/awx -c awx-web > /mnt/log/awx-web.txt

- name: Get Logs awx-task
  shell: kubectl -n awx  logs deploy/awx -c awx-task > /mnt/log/awx-tasks.txt

- name: Get Logs awx-ee
  shell: kubectl -n awx  logs deploy/awx -c awx-ee > /mnt/log/awx-ee.txt 

- name: Get Logs Nginx error
  shell: cat /var/log/nginx/error.log > /mnt/log/error.txt
  
- name: Get Logs Nginx access.log 
  shell: cat /var/log/nginx/access.log > /mnt/log/access.txt
  
- debug:
    msg: "Логи по ссылке: http://{{ip}}:8888/log/ "


