---
- name: delete k3s file
  shell: rm -rf k3s
  args:
    chdir: /usr/bin
    
- name: delete file k3s-selinux 
  shell: rm -rf k3s-selinux-0.4-1.el7.noarch.rpm
  args:
    chdir: /usr/bin
   
- name: delete file install.sh
  shell: rm -rf install.sh
  args:
    chdir: /usr/bin
 
- name: delete k3s
  shell: ./k3s-uninstall.sh
  args:
    chdir: /usr/bin
    
- name: delete k3s-selinux
  shell: yum remove k3s-selinux.noarch -y

- name: delete folder's awx-operator
  shell: rm -rf  awx-operator  awx-operator.zip
  args:
    chdir: /root



    

