---
- name: stop server
  include_tasks: control-stop-console-wf.yml

- name: start server
  include_tasks: control-start-console-wf.yml
  
- name: start app
  include_tasks: control-start-app-wf.yml
