
  - name: Create unpack directory
    file:
      path: "tmp/unpacked"
      state: directory
      recurse: yes
    register: unpackdir


  - name: Unzip distrib
    unarchive:
      src: /tmp/distrib.zip
      dest: "{{ unpackdir.path }}"
      remote_src: yes
    # when: no

  - name: subfolder
    shell:
      chdir: "{{ unpackdir.path }}"
      cmd: ls | grep wildfly
    register: subfolder
    failed_when: no

  - set_fact:
      distro_root_dir: "{{ subfolder.stdout if subfolder.stdout!='' else '' }}"

  - name: version from zip
    shell: >
      {{ unpackdir.path }}/{{ distro_root_dir }}/bin/standalone.sh -version | grep WildFly | sed -r 's/^[^(]+ ([0-9\.]+Final).+$/\1/'
    register: wildfly_version
