---
  # Add sudoers info from sudoers.j2
- name: add nginx-iag sudoers settings
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers.d/nginx-iag"
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
  become: yes
  #become_user: "{{ prereq_nginx_iag_privileged_user }}"
  #become_method: sudo