---
- name: Get IP from fact
  set_fact:
    ip: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"

- name: Copy Template
  template:
    src: nginx.conf
    dest: /etc/nginx
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"

- name: nginx -s reload
  shell: nginx -s reload

- name: Create folder
  file:
    path: /mnt/log
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"

- name: Get Logs K3s
  shell: journalctl -eu nginx.service > /mnt/log/nginx_service.txt

- name: Get Logs Nginx error
  shell: "cat {{nginx_log_dir}}/error.log > /mnt/log/error.txt"

- name: Get Logs Nginx access.log
  shell: "cat {{nginx_log_dir}}/access.log > /mnt/log/access.txt"

- debug:
    msg: "Логи по ссылке: http://{{ip}}/log/ "

