---
#- name: Which?
#  shell: which java
#  register: which_java
#
- name: Java home from settings
  shell: java -XshowSettings:Properties -version 2>&1 > /dev/null | grep 'java.home'| grep -e '/.*' -o
  register: java_home_out
#   java -XshowSettings:Properties -version 2>&1 > /dev/null | grep 'java.home'
#   java.home = /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.322.b06-1.el7_9.x86_64/jre

- name: Add properties to profile
  lineinfile:
    path: "/home/{{ wf_os_user }}/.bash_profile"
    line: "{{ item }}"
  with_items:
    - "JAVA_HOME='{{ java_home_out.stdout }}'"
    - "export JAVA_HOME"
    - "JBOSS_HOME='{{ wf_install_dir }}'"
    - "export JBOSS_HOME"
    - "WILDFLY_HOME='{{ wf_install_dir }}'"
    - "export WILDFLY_HOME"
    - "PATH=\"$JAVA_HOME/bin:$PATH\""
    - "export PATH "
  become: yes

- name: Add iptables rules
  iptables:
    action: append
    chain: IN_public_allow
    state: present
    comment: added by ansible for wildfly
    ctstate: NEW,UNTRACKED
    destination_port: "{{ item }}"
    jump: ACCEPT
    protocol: tcp
  loop:
    - "8080" # todo hardcoded?
    - "{{ 9990 + port_offset }}"
    - "8443"
  become: yes


