- name: Останов экземпляра БД с patroni
  service:
    name: patroni
    state: stopped
  become_user: root
  become: yes

#rm -r /usr/local/pgsql/*
#cp -r ~/pgsql.<old_version>/* /usr/local/pgsql
- name: Восстановление исполняемых файлов
  copy:
    remote_src: true
    src: ~/pgsql.{{ pgse_version_from }}/
    dest: /usr/local/pgsql

- name: Запуск экземпляра БД с patroni
  service:
    name: patroni
    state: started
  become_user: root
  become: yes

- name: Включить autofailover в патрони
  shell: |
    source ~/.bash_profile
    patronictl -c /etc/patroni/postgres.yml resume
