---
- hosts: "{{ hosts_group_WF }}"
  serial: "{{ serial | default('100%') }}"
  tasks:

    - meta: end_play
      when: externalString is not defined and hosts_group_WF is not defined

    - name: Check core service
      shell: systemctl show "{{ wf_service }}" | grep BindsTo
      register: core_service
      #when: wf_service is defined and (((externalString is defined) and externalString != "") or ((hosts_group_WF is defined) and hosts_group_WF != ""))
      when: wf_service is defined

    - name: Set variable
      set_fact:
        double_service: true
      #when: wf_service is defined and core_service is defined  and core_service.rc is defined and core_service.rc == 0 and (((externalString is defined) and externalString != "") or ((hosts_group_WF is defined) and hosts_group_WF != ""))
      when: wf_service is defined and core_service.rc == 0

    - name: Restart console WF
      include_role:
        name: wildfly
        tasks_from: control-restart-wf-enable-app
      when: ( externalString is defined and externalString != "" ) or ( hosts_group_WF is defined and hosts_group_WF != "" )