---
# install_nginx default variables
install_dir: "/opt/nginx"
nginx_conf_dir: "/etc/nginx"
nginx_http_port: "80"
nginx_user: "nginx"
nginx_group: "nginx"
nginx_user_pwd: "nginx"
nginx_log_dir: "/var/log/nginx"
nginx_os_user_pwd: "nginx"
nginx_docroot: "{{ install_dir }}/html"
array_label_disk: [b,c,d,e,f]
#nginx_docroot: "{{ install_dir }}/docroot"


service_state: restarted #started #stopped
